export const appRoutes = {
  register: '/register',
  login: '/login',
  dashboard: '/dashboard',
  adminResidents: '/admin/residents',
  adminStaff: '/admin/staff',
  adminRequests: '/admin/requests',
  adminIncidents: '/admin/incidents',
  adminLogs: '/admin/logs',
  adminActivities: '/admin/activities',
  adminArchives: '/admin/archives',
  requestRecord: '/request-record',
  recordsQueue: '/records-queue',
  reportProblem: '/report-problem',
  secretaryRequests: '/secretary-requests',
  processRequest: '/process-request',
  secretaryReports: '/secretary-reports',
  archiveRecords: '/archive-records',
  certificateIncidentArchives: '/certificate-incident-archives',
  barangayRecordArchives: '/barangay-record-archives',
  activityLogs: '/activity-logs',
  profile: '/profile',
} as const
